// leave off @2x/@3x
const images = {
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  iconHome: require('../Images/Icons/HomeIcon.png'),
  iconAccount: require('../Images/Icons/IconAccount.png'),
  iconJournal: require('../Images/Icons/IconJournal.png'),
  backgroundAuth: require('../Images/BackgroundAuth.png'),
  backgroundMain: require('../Images/BackgroundMain.png'),
  coverMain: require('../Images/CoverMain.png'),
  berhitung: require('../Images/ItemHome/Berhitung.png'),
  curhat: require('../Images/ItemHome/Curhat.png'),
  fotofavorit: require('../Images/ItemHome/FotoFavorit.png'),
  jalanyuk: require('../Images/ItemHome/JalanYuk.png'),
  kalimatbijak: require('../Images/ItemHome/KalimatBijak.png'),
  koneseling: require('../Images/ItemHome/Konseling.png'),
  mediasi: require('../Images/ItemHome/Mediasi.png'),
  iconNotification: require('../Images/Icons/IconNotification.png'),
}

export default images
